### ISSUE TITLE
Windows Install Script Doesn't Work

### ISSUE THREAD

**Issue by joe-camp-nelnet** [komodorio/komocli#26]
The Komodor UI provides instructions on how to use port forwarding using the Komodor CLI:

<img src="https://github.com/komodorio/komocli/assets/153004086/ca7aa201-95ea-4332-a48d-15c7ea424235" width="300px" />

However, there are several issues with your windows / powershell install script. It fails to run on powershell core on windows.

https://github.com/komodorio/komocli/blob/main/scripts/install.ps1

1. The script is written to detect the operating system, but I presume this PowerShell script is really only intended for windows-based installation.  The script could be simplified for that use case, unless you intend it to be usable for people running PowerShell on Linux.  But for Linux users I'd assume the bash install script is preferable.

2. The `Get-Arch` function depends on the `Get-WmiObject` function which is only available in "PowerShell for Windows" and not in the PowerShell Core.  Even if the script is intended only for windows installations, it should be assumed that developers are likely using the latest version of PowerShell Core.  The `Get-Arch` function could be updated as follows:

```pwsh
function Get-Arch {
    $systemType = (Get-CimInstance -ClassName CIM_ComputerSystem).SystemType
    if ($systemType -match 'x64') {
        "amd64"
    }
    elseif ($systemType -match 'ARM') {
        "arm64"
    }
    elseif ($systemType -match 'x86') {
        "386"
    }
}
```

3. The script downloads the `windows_amd64.exe` asset but then saves it as a `.tar.gz` file.  The file should be saved as an `.exe` file. It does not need to be extracted from an archive.  The script also assumes it can extract the file using `tar` which is not common on windows, but that is irrelevant, and that dependency should not be needed since the file downloaded is the raw executable.

4. The script stores the file in `$env:APPDATA` but it seems like it would be more typical to store it in a sub-folder beneath that location at least.

5. The script does not add the file location to the PATH. For completeness, either update the path or provide instructions to users that they'd need to edit their path themselves in order to use the tool from the terminal.

**Comment by amit9192** [comment]
Hi @joe-camp-nelnet,

Amit from the Komodor product team here.
Thanks for reporting this and providing those valuable inputs!

I've fixed the script to work with the binary rather than `.tar.gz` file
I've also implemented the rest of your suggestions and merged them into the main branch
